---
language: python
services: docker

env:
  matrix:
    - MOLECULE_DISTRO: ubuntu1604
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: debian8
    - MOLECULE_DISTRO: debian9
    - MOLECULE_DISTRO: centos7

install:
  - sudo modprobe ip6_tables
  - pip install molecule yamllint ansible-lint flake8 docker pytest testinfra

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
