---
# handlers file for check_mk agent
- name: Restart firewalld
  service:
    name: firewalld
    state: restarted

- name: Check_mk activate changes via WATO API
  check_mk:
    server_url: "{{ check_mk_agent_monitoring_host_url }}"
    username: "{{ check_mk_agent_monitoring_host_wato_username }}"
    secret: "{{ check_mk_agent_monitoring_host_wato_secret }}"
    activate_changes: true
  delegate_to: localhost
